# Generated by Django 4.0.4 on 2022-04-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdpApp2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regid', models.IntegerField()),
                ('purch_amt', models.DecimalField(decimal_places=3, max_digits=100)),
                ('salesman_id', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
