# Generated by Django 4.0.4 on 2022-04-30 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdpApp2', '0003_porders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
